databases:
  - name: techtrendsdb
    plan: free
    databaseName: techtrends
    user: techtrends

services:
  - type: web
    plan: free
    name: techtrends
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn techtrends.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: techtrendsdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4